version: "2"

services:
  gitea:
    image: gitea/gitea:1.19
    hostname: gitea.local
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_metastore:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    mem_limit: 256m
    networks:
      backnet:
    # port 3000, 22
    depends_on:
      - gitea_metastore
    volumes:
      - gitea_data:/data
      - ../common/hosts:/etc/hosts:ro # to make webhooks work
    # alo need this config in /gitea/custom/conf/app.ini
    #[webhook]
    #ALLOWED_HOST_LIST=private
    
  gitea_metastore:
    image: bitnami/postgresql:15
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=gitea
      - POSTGRESQL_USERNAME=gitea
      - POSTGRESQL_PASSWORD=gitea
      - ALLOW_EMPTY_PASSWORD=no
    hostname: postgresql
    mem_limit: 128m
    networks:
      backnet:

volumes:
  postgresql_data:
  gitea_data:

networks:
  backnet:
    external: true