version: "2"
services:
  nginx:
    image: nginx:stable-alpine-slim
    mem_limit: 32m
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      backnet:
networks:
  backnet:
    external: true